### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by rooler3** [WISEPLAT/backtrader_bybit#2]
Traceback (most recent call last):
  File "C:\Users\vitya\PycharmProjects\binance_bot\04 - Offline Backtest.py", line 305, in <module>
    cerebro.run()  # Запуск торговой системы
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\cerebro.py", line 1132, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\cerebro.py", line 1303, in runstrategies
    self._runnext(runstrats)
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\cerebro.py", line 1635, in _runnext
    strat._next()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\strategy.py", line 347, in _next
    super(Strategy, self)._next()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\lineiterator.py", line 263, in _next
    indicator._next()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\lineiterator.py", line 263, in _next
    indicator._next()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\linebuffer.py", line 621, in _next
    self.nextstart()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\lineroot.py", line 144, in nextstart
    self.next()
  File "C:\Users\vitya\PycharmProjects\binance_bot\venv\lib\site-packages\backtrader\linebuffer.py", line 744, in next
    self[0] = self.operation(self.a[0], self.b[0])
ZeroDivisionError: float division by zero
Не запускается приложение в определенное время, 2 дня такое было, в 1 й день не обратил внимание во сколько, во второй день 20:05-20:10. Код не редактировал само прошло.
Это от backtrader_binance извиняюсь не туда написал

**Comment by WISEPLAT** [comment]
"Это от backtrader_binance извиняюсь не туда написал"
