### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by unitydd17** [WISEPLAT/backtrader_bybit#3]
У меня ошибка деления на ноль в файле
 08 - Offline Backtest Margin Trade with Leverage 50x - Linear Trade.py
при лайв трейдинге(тоесть не тест а все настроено на реальную торговлю на бирже)
эти строки раскоментированы 

broker = store.getbroker()
cerebro.setbroker(broker)

data = store.getdata(timeframe=bt.TimeFrame.Minutes, compression=1, dataname=symbol, start_date=from_date, LiveBars=True)  # set True here - if you need to get live bars
    data2 = store.getdata(timeframe=bt.TimeFrame.Minutes, compression=1, dataname=symbol2, start_date=from_date, LiveBars=True)  # set True here - if you need to get live bars

лайв бары выставлены в тру

сначала думал может изза того что на бирже у usdt на счету 0, закинул $10 - но всеравно таже ошибка

Что я делаю не так?)

Exception has occurred: ZeroDivisionError
float division by zero
  File "D:\Projects\bybit\ByBitBot\backtrader_bybit\StrategyExamplesBybit\08 - Offline Backtest Margin Trade with Leverage 50x - Linear Trade.py", line 185, in <module>
    result = cerebro.run()  # Launching a trading system
             ^^^^^^^^^^^^^

**Comment by WISEPLAT** [comment]
Привет, пришли плиз полный лог ошибки.

**Comment by unitydd17** [comment]
Привет!, присылаю =)

- BTCUSDT - History data from 2024-03-22 01:12:56 + 200 rows - Ok
- BTCUSDT - History data from 2024-03-22 04:31:00 + 200 rows - Ok
- BTCUSDT - History data from 2024-03-22 07:50:00 + 200 rows - Ok
- BTCUSDT - History data from 2024-03-22 11:09:00 + 200 rows - Ok
- ETHUSDT - History data from 2024-03-22 01:12:56 + 200 rows - Ok
- ETHUSDT - History data from 2024-03-22 04:31:00 + 200 rows - Ok
- ETHUSDT - History data from 2024-03-22 07:50:00 + 200 rows - Ok
- ETHUSDT - History data from 2024-03-22 11:09:00 + 200 rows - Ok
Traceback (most recent call last):
  File "d:\Projects\bybit\ByBitBot\backtrader_bybit\StrategyExamplesBybit\08 - Offline Backtest Margin Trade with Leverage 50x - Linear Trade.py", line 185, in <module>
    result = cerebro.run()  # Launching a trading system
             ^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\cerebro.py", line 1132, in run
    runstrat = self.runstrategies(iterstrat)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\cerebro.py", line 1303, in runstrategies
    self._runnext(runstrats)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\cerebro.py", line 1635, in _runnext
    strat._next()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\strategy.py", line 350, in _next
    self._next_analyzers(minperstatus)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\strategy.py", line 388, in _next_analyzers
    analyzer._prenext()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\analyzer.py", line 320, in _prenext
    self.on_dt_over()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\backtrader\analyzers\drawdown.py", line 188, in on_dt_over
    self.dd = dd = 100.0 * (self.peak - value) / self.peak
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by WISEPLAT** [comment]
Закомментируй это:
    # Add Finance metrics of quality our strategy on historical data (backtest and results)
    # cerebro.addanalyzer(btanalyzers.SQN, _name='SQN')
    # cerebro.addanalyzer(btanalyzers.VWR, _name='VWR', fund=True)
    # cerebro.addanalyzer(btanalyzers.TimeDrawDown, _name='TDD', fund=True, timeframe=bt.TimeFrame.Days)
    # cerebro.addanalyzer(btanalyzers.DrawDown, _name='DD', fund=True)
    # cerebro.addanalyzer(btanalyzers.Returns, _name='R', fund=True, timeframe=bt.TimeFrame.Days)
    # cerebro.addanalyzer(btanalyzers.AnnualReturn, _name='AR', )
    # cerebro.addanalyzer(btanalyzers.SharpeRatio, _name='SR')
    # cerebro.addanalyzer(btanalyzers.TradeAnalyzer, _name='TradeAnalyzer')

**Comment by unitydd17** [comment]
Спасибо, помогло!)
